### ISSUE TITLE
Is the Docker FS/Image cached and where is it cached? 

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry-incubator/diego-design-notes#30]
Can we add this to the Docker Design notes? 
https://github.com/cloudfoundry-incubator/diego-design-notes/blob/master/docker-support.md

**Comment by ematpl** [comment]
Hi, @rjain-pivotal,

When Diego runs a Task or LRP with a Docker image as a rootfs (as it does when it runs a Docker-image-based CF app), the only caching of the Docker image layers occurs on the hosts that run the resulting containers. Garden-linux currently also aggressively garbage-collects unused layers after every container teardown unless they are explicitly white-listed in its `persistent_image_list` property; at some point, it may instead use an LRU policy to prune unused layers once it hits a certain disk-usage quota.

I'll see about including some of that info in the Docker support notes here, or better yet in the CF docs at http://docs.cloudfoundry.org/concepts/docker.html.

Thanks,
Eric
