### ISSUE TITLE
receptor should be removed

### ISSUE THREAD

**Issue by bleach** [cloudfoundry-incubator/diego-design-notes#33]
receptor was removed from diego by cloudfoundry-incubator/diego-release@46c5472456a7307730981d7c5054915346699622, but is referred to:
- in the diagram
- in README.md
- ssh-access-and-policy.md

**Comment by ematpl** [comment]
Thanks, @bleach. I think I've revised the receptor and lattice out of everything important here. Closing.

Best,
Eric, CF Runtime Diego PM

**Comment by bleach** [comment]
Thanks, much better!
